name: borsa

profile: borsa

config-version: 2

model-paths: ["dbt/models"]
seed-paths: ["dbt/seeds"]
test-paths: ["dbt/tests"]
analysis-paths: ["dbt/analysis"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]
docs-paths: ["dbt/docs"]
asset-paths: ["dbt/assets"]

packages-install-path: "dbt/packages"

clean-targets: ["dbt/target"]

vars:
  smas: [0, 5, 10, 20, 40]
  bars_ago: [1, 2, 3, 4, 5]
  max_buy_value: 10_000
  max_buys_per_day: 1
  trailstop: -0.005
  target_profit: 1
  buy_after_minutes: 5
  sell_by_minutes: 120
  sell_conditions: "false"
  include_optimal_strategy: "true"
  strategies: [
    # {
    #   id: "test1",
    #   buy: "sma0lag2 < sma10lag2 and sma0 > sma10 and sma5cntup2 and sma0 > sma5",
    # },
    {
      id: "test2",
      buy: "(sma0lag2 < sma10lag2 and sma0 > sma10 and sma5cntup2 and sma0 > sma5) 
            or (sma0cntup2 and price > sma5 and sma5 > sma10 and sma10 > sma20)",
    },
    # {
    #   id: "test3",
    #   buy: "sma5cntup3",
    # }
  ]

# Dev is for backtesting where tables are faster
# Prod is for trading where views are faster
models:
  borsa:
    intermediate:
      +materialized: "{{ 'table' if target.name == 'dev' else 'view' }}"
    reports:
      +materialized: "{{ 'table' if target.name == 'dev' else 'view' }}"