name: borsa

profile: borsa

config-version: 2

model-paths: ["dbt/models"]
seed-paths: ["dbt/seeds"]
test-paths: ["dbt/tests"]
analysis-paths: ["dbt/analysis"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]
docs-paths: ["dbt/docs"]
asset-paths: ["dbt/assets"]

log-path: "dbt/logs"
target-path: "dbt/target"
packages-install-path: "dbt/packages"

clean-targets: ["dbt/target"]

vars:
  smas: [0, 5, 10, 20, 40]
  bars_ago: [1, 2, 3, 4, 5]

models:
  borsa:
    trade:
      +materialized: table